# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [firefox]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: yarn && yarn build

      - name: Set version number
        run: yarn set-version $GITHUB_RUN_NUMBER

      - name: make output folder
        run: mkdir packaged

      - name: zip for chrome
        run: yarn zip:chrome

      - name: zip for firefox
        run: yarn zip:firefox

      - name: ls
        run: ls packaged

#       - name: Chrome Addon Action
#         uses: trmcnvn/chrome-addon@v2
#         with:
#           extension: djejlpbhhhhidocammjkigbcpdcggmgj
#           zip: packaged/chrome.zip
#           client-id: ${{ secrets.CHROME_CLIENT_ID }}
#           client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
#           refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: "web-ext build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: dist

      - name: "web-ext sign"
        id: web-ext-sign
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          source: ${{ steps.web-ext-build.outputs.target }}
          channel: unlisted
          apiKey: ${{ secrets.AMO_SIGN_KEY }}
          apiSecret: ${{ secrets.AMO_SIGN_SECRET }}

      - name: ls
        run: ls
